feat: support link text
prismicio/prismic-react pull request #205
Opened 2024-08-28 18:16 UTC by xrutayisire

Resolves: [DT-2272](https://linear.app/prismic/issue/DT-2272/aadev-i-can-use-prismic-sdks-with-support-link-text)

## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

- Support link text 
- Update example with new usage

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

2024-08-28 18:17 UTC, xrutayisire commented on test/react-server/PrismicRichText.test.tsx
> +			id: "",
I don't understand why I had to add that, it was crashing but not really related to my work, I guess related to an update on prismic-client. WDYT @angeloashmore?

2024-08-29 00:58 UTC, angeloashmore requested changes
Looks good! I left a few suggestions, none of which are blocking.

I'm going to mark the PR as "Request changes" because we should publish `@prismicio/client` first and update the version here before merging. Let me know if you'd like to handle that a different way though.

2024-08-29 00:58 UTC, angeloashmore commented on src/react-server/PrismicLink.tsx
> +	children?: React.ReactNode;
```suggestion
	/**
	 * The children to render for the link. If no children are provided, the
	 * link's `text` property will be used.
	 */
	children?: React.ReactNode;
```

2024-08-29 00:58 UTC, angeloashmore commented on src/react-server/PrismicLink.tsx
> +	if (field && "text" in field) {
💡 #idea: `@prismicio/client`'s `isFilled` helpers declaratively check if a field is filled. In this case, `field && "text" in field` only checks that the field is filled, so `isFilled` might be a better fit.

```suggestion
	if (field && isFilled.link(field)) {
```

`isFilled` can be imported from `@prismicio/client`:

```ts
import { isFilled } from "@prismicio/client
```

2024-08-29 00:58 UTC, angeloashmore commented on src/react-server/PrismicLink.tsx
> +			{children || text}
💡 #idea: We might want to use `??` rather than `||` to handle the case where `""` is used as a child. WDYT?

2024-08-29 00:58 UTC, angeloashmore commented on test/PrismicLink.test.tsx
> +it("if link text is provided without children, render link with the text", async (ctx) => {
💡 #idea: This phrasing might be easier to understand:

```suggestion
it("renders the link's text if no children are provided", async (ctx) => {
```

2024-08-29 00:58 UTC, angeloashmore commented on test/PrismicLink.test.tsx
> +	});
💡 #idea: Small optimization that shortens the test:

```suggestion
	const model = ctx.mock.model.link({ text: true });
	const field = ctx.mock.value.link({ type: "Web", model });
```

2024-08-29 00:58 UTC, angeloashmore commented on test/PrismicLink.test.tsx
> +it("if link text is provided with children, render link with given children", async (ctx) => {
💡 #idea: This phrasing might be easier to understand:

```suggestion
it("renders the given children, overriding the link's text", async (ctx) => {
```

2024-08-29 00:58 UTC, angeloashmore commented on test/PrismicLink.test.tsx
> +	});
💡 #idea: Small optimization that shortens the test:

```suggestion
	const model = ctx.mock.model.link({ text: true });
	const field = ctx.mock.value.link({ type: "Web", model });
```

2024-08-29 00:58 UTC, angeloashmore commented on test/react-server/PrismicRichText.test.tsx
> +			id: "",
You're right; it's related to updating `@prismicio/client`. The `id` and `edit` asset properties were added relatively recently and probably didn't propagate to this library yet. We should be good after this PR. 🙂

2024-08-29 08:01 UTC, xrutayisire commented on src/react-server/PrismicLink.tsx
> +	if (field && "text" in field) {
I was even able to do: `const text = isFilled.link(field) ? field.text : undefined;`!

2024-08-29 08:03 UTC, xrutayisire commented on src/react-server/PrismicLink.tsx
> +			{children || text}
We discussed it with @lihbr, we wondered the same, but we believe that it's not logical to not write the text if it's there, and you passed down "" or 0. 

We think we could review it depending on feedback + if you really don't want the text in some case you can filter it out from the `field`. WDYT?

2024-08-29 08:06 UTC, xrutayisire commented on test/PrismicLink.test.tsx
> +	});
Done, thanks, better 🙂

2024-08-29 08:06 UTC, xrutayisire commented on test/PrismicLink.test.tsx
> +it("if link text is provided with children, render link with given children", async (ctx) => {
Done, thanks, better 🙂

2024-08-29 08:06 UTC, xrutayisire commented on test/PrismicLink.test.tsx
> +	});
Done, thanks, better 🙂

2024-08-29 08:06 UTC, xrutayisire commented on test/PrismicLink.test.tsx
> +it("if link text is provided without children, render link with the text", async (ctx) => {
Done, thanks, better 🙂

2024-08-29 08:06 UTC, xrutayisire commented on src/react-server/PrismicLink.tsx
> +	if (field && "text" in field) {
Done, thanks, better 🙂

2024-08-29 08:06 UTC, xrutayisire commented on src/react-server/PrismicLink.tsx
> +	children?: React.ReactNode;
Done, thanks, better 🙂

2024-08-29 08:08 UTC, xrutayisire commented
On the PR status, we could go with `approved` or not anyway. We have the release process that will take in place after, where we need to update all of our work with latest packages. If it's not approved and with the time difference, it may mean we release without clear green approval on your side. 
But if you comment that it is good except the packages, I guess we would be good then and understand we can release 🙂

2024-08-30 00:24 UTC, angeloashmore commented on src/react-server/PrismicLink.tsx
> +			{children || text}
With `children || text`, using `{0}` or `{""}` as a child wouldn't work. Those kinds of children could come from programmatically created values. The use of `||` is implicit and can lead to unexpected results. I can't think of a reason why we would want to treat `0` and `""` as special cases, which we are by using `||` over `??`.

Using `{0}` or `{""}` as an override would currently require this:

```tsx
declare const field: LinkField

field.text = 0.toString()
// Or field.text = ""

<PrismicLink field={field} />
```

We already have a way to override the field's text, and that is through `children`:

```tsx
<PrismicLink field={field}>My override</PrismicLink>
<PrismicLink field={field}>{0}</PrismicLink>
<PrismicLink field={field}>{""}</PrismicLink>
```

That usage is the same as for fields that don't have a `text` property:

```tsx
<PrismicLink field={field}>My link</PrismicLink>
<PrismicLink field={field}>{keyTextField}</PrismicLink>
```

If I set a child, it means I definitely want that as the child. We always give access to `link.text` for manual handling, which can be used with the same conventions shown above.

```tsx
<PrismicLink field={field}>{link.text ?? "A fallback"}</PrismicLink>
```

This makes me think we could even consider using `"children" in props` to determine if we use `link.text`. In other words, if a child is given, always use it. It would prevent the following strange case:

```tsx
```

In general, we should strive to have only one way to perform tasks. Multiple solutions can lead to confusion and difficulty in troubleshooting. In this case, it means treating both `children` and manually setting `field.text` as viable solutions may be a poor choice.

2024-08-30 00:33 UTC, angeloashmore commented
@xrutayisire Could we discuss and conclude https://github.com/prismicio/prismic-react/pull/205#discussion_r1737542906 before I approve this and the other SDK PRs? You're right about handling the version numbers after the approval.

2024-08-30 08:46 UTC, lihbr commented on src/react-server/PrismicLink.tsx
> +			{children || text}
Agreed, this seems more "pure" all things considered!

2024-08-30 12:00 UTC, xrutayisire commented on src/react-server/PrismicLink.tsx
> +			{children || text}
Thank you for the detailed answer done 👍

2024-08-30 20:14 UTC, angeloashmore approved these changes
Looks good!

2024-09-13 03:02 UTC, angeloashmore approved these changes
Looks good!

2024-09-13 03:02 UTC, angeloashmore commented on src/react-server/PrismicLink.tsx
> +					: Object.keys(field).length > 1) &&
🎉 #nice: The dev message code is still a little weird, but this is a nice and simple to make your new work compatible. 😄

2024-09-27 10:44 UTC, merged